"""Add do_not_drop to alignment table

Revision ID: e116c56474a2
Revises: 20ac221144da
Create Date: 2024-08-22 16:39:28.775292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e116c56474a2'
down_revision = '20ac221144da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alignments', sa.Column('do_not_drop', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alignments', 'do_not_drop')
    # ### end Alembic commands ###
